feat : Added Sponsor Models
iamareebjamal/open-event-android-sdk pull request #8
Opened 2017-06-18 11:11 UTC by shreyasnbhat

Added sponsor models.

2017-06-18 11:12 UTC, shreyasnbhat commented
@iamareebjamal Please review.

2017-06-18 12:44 UTC, iamareebjamal requested changes

2017-06-18 12:44 UTC, iamareebjamal commented on src/main/java/openevent/Application.java
> +=======
some merge conflicts are still there

2017-06-18 17:14 UTC, arp95 commented on src/main/java/openevent/model/api/ApiSponsor.java
> +	@JsonProperty
@iamareebjamal 
what is the use of this class?
we are using sponser.java as a model right, so the object sponser will be of this type and we will take data through that.
what exactly does this class do?

2017-06-18 17:28 UTC, arp95 commented on src/main/resources/sponsors.json
> +        "logo": "/images/sponsors/Python_10.png",
shouldnt this be "logo-url", according to the nextgen api format?

2017-06-18 17:33 UTC, iamareebjamal commented on src/main/java/openevent/model/api/ApiSponsor.java
> +	@JsonProperty
This is new API class

2017-06-18 17:33 UTC, iamareebjamal commented on src/main/resources/sponsors.json
> +        "logo": "/images/sponsors/Python_10.png",
nextgen api models are present in /api/ folder

2017-06-19 01:30 UTC, shreyasnbhat commented on src/main/java/openevent/Application.java
> +=======
Will fix.

2017-06-19 01:40 UTC, shreyasnbhat commented
@iamareebjamal Ready for review.

2017-06-19 05:05 UTC, Shailesh351 commented on src/main/resources/api/sponsors.json
> +        "name": "Goolgle is a Tech Corp"
I think you have added description in name and name in description :sweat_smile:

2017-06-19 05:07 UTC, shreyasnbhat commented on src/main/resources/api/sponsors.json
> +        "name": "Goolgle is a Tech Corp"
I guess it doesn't matter when the main motive is to do model conversion. 
Will keep this in mind the next time. 👍

2017-06-19 05:13 UTC, Shailesh351 approved these changes

2017-06-19 05:18 UTC, arp95 approved these changes

2017-06-19 06:03 UTC, merged